
	NDefines.NWiki.BASE_URL = ""
	NDefines.NWiki.FORUM_URL = "https://millennium_dawn.gitlab.io/modernday4.gitlab.io"

	NDefines.NMapIcons.STATES_PRIORITY_VICTORY_POINTS = 0
	
	NDefines.NGraphics.PROVINCE_NAME_DRAW_DISTANCE = 800.0
	NDefines.NGraphics.DRAW_SHADOWS_CUTOFF = 200
	NDefines.NGraphics.DRAW_SHADOWS_FADE_LENGTH = 80
	
	--GRADIENT_BORDERS_COUNTRY_CENTER_THICKNESS = 2.0, -- The center gradient is linear 1/255 per pixel for this many pixels --1
	--GRADIENT_BORDERS_THICKNESS_COUNTRY_HIGH = 25.0, --25
	NDefines.NGraphics.GRADIENT_BORDERS_THICKNESS_STATE = 50.0 --11
	NDefines.NGraphics.GRADIENT_BORDERS_THICKNESS_SUPPLY_AREA_B = 15.0 --20
	NDefines.NGraphics.GRADIENT_BORDERS_THICKNESS_STRATEGIC_REGIONS = 45.0 --150
	NDefines.NGraphics.GRADIENT_BORDERS_OUTLINE_CUTOFF_STRATEGIC_REGIONS = 0.999
	NDefines.NGraphics.STRATEGIC_AIR_COLOR_NEUTRAL = {165.0/255, 165.0/255, 165.0/255, 1} -- {140.0/255, 131.0/255, 119.0/255, 1}
	NDefines.NGraphics.STRATEGIC_NAVY_COLOR_NEUTRAL = {41.0/255, 45.0/255, 64.0/255, 1} -- {0.3, 0.3, 0.3, 0}
	NDefines.NGraphics.COUNTRY_FLAG_TEX_MAX_SIZE = 512							-- Vanilla is 256, Tweak dependly on amount of countries. Must be power of 2. No more then 2048.
	NDefines.NGraphics.COUNTRY_FLAG_SMALL_TEX_MAX_SIZE = 128					-- Vanilla is 64, Tweak dependly on amount of countries. Must be power of 2. No more then 2048.
	NDefines.NGraphics.COUNTRY_FLAG_STRIPE_TEX_MAX_WIDTH = 10					-- Vanilla is 10
	NDefines.NGraphics.COUNTRY_FLAG_STRIPE_TEX_MAX_HEIGHT = 2048				-- Vanilla is 2048
	NDefines.NGraphics.COUNTRY_FLAG_LARGE_STRIPE_MAX_WIDTH = 41					-- Vanilla is 41
	NDefines.NGraphics.COUNTRY_FLAG_LARGE_STRIPE_MAX_HEIGHT = 8192				-- Vanilla is 8192
	NDefines.NGraphics.VICTORY_POINT_MAP_ICON_AFTER = {0, 4}
	NDefines.NGraphics.VICTORY_POINT_MAP_ICON_TEXT_CUTOFF = {180, 420, 1000}
	NDefines.NGraphics.VICTORY_POINTS_DISTANCE_CUTOFF = {180, 420, 1000}
	NDefines.NGraphics.NAVALBASE_ICON_DISTANCE_CUTOFF = 900			  
	NDefines.NGraphics.CAPITAL_ICON_CUTOFF = 1000
	NDefines.NGraphics.MAP_ICONS_GROUP_CAM_DISTANCE = 120.0
	NDefines.NGraphics.MAP_ICONS_STATE_GROUP_CAM_DISTANCE = 330.0
	NDefines.NGraphics.MAP_ICONS_STRATEGIC_GROUP_CAM_DISTANCE = 600
	NDefines.NGraphics.MAPICON_GROUP_STRATEGIC_SIZE = 600
	NDefines.NGraphics.MAP_ICONS_COARSE_COUNTRY_GROUPING_DISTANCE = 200
	NDefines.NGraphics.MAP_ICONS_COARSE_COUNTRY_GROUPING_DISTANCE_STRATEGIC = 800
	NDefines.NGraphics.CAMERA_OUTSIDE_MAP_DISTANCE_TOP = 100.0
	NDefines.NGraphics.CAMERA_OUTSIDE_MAP_DISTANCE_BOTTOM = 100.0
	NDefines.NGraphics.CAMERA_ZOOM_SPEED = 12
	NDefines.NGraphics.CAMERA_ZOOM_KEY_SCALE = 0.01
	NDefines.NGraphics.CAMERA_ZOOM_SPEED_DISTANCE_MULT = 50.0
	
	NDefines.NFrontend.CAMERA_LOOKAT_SETTINGS_X = 2058.0
	NDefines.NFrontend.CAMERA_MIN_HEIGHT = 30.0